### PR TITLE
Fix: Handle zero and boolean values properly in options array

### LINKED ISSUE #87: Having a data of 0 causing the placeholder to stay on
**Describe the bug**
Having a data of 0 causing the placeholder to stay on. Using version 1.3.18

**Expected behavior**
The placeholder should be hidden

**Screenshots**
Screenshot 2024-09-09 at 16 06 55

**Smartphone**
 - Device: Android
 - OS: API 34

### PR DESCRIPTION
**Pull request by azeezat**
# Description

This PR addresses issues with Zeros and boolean values in options array that were initially not well handled.

Fixes #87 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: src/utils/index.ts [hunk 1]
```diff
@@ -55,7 +55,7 @@ export const getLabelsOfSelectedItems = ({
         (item: TFlatListItem) => item[optionValue] === element
       )?.[optionLabel];
 
-      if (selectedItemLabel) {
+      if (selectedItemLabel !== '') {
```
Comment (kofiarkoh) [inline src/utils/index.ts:58]: @azeezat , since `selectedItemLabel` could be `undefined`, I think this should be `if(selectedItemLabel){...}` because `undefined !== ''` will produce `true`

Comment (azeezat) [reply src/utils/index.ts:58]: @kofiarkoh Your observation is correct. This change is supposed to handle some edge cases. Using the Logical NOT Operator (!) negates the value of the operand. So in a scenario where the value of the label is 0 or false, the logic fails.

See example below

```js
options = [
    {label: 0, value: 0},
    {label: 1, value: false},
    {label: 2, value: 2},
  ]
```

Comment (kofiarkoh) [reply src/utils/index.ts:58]: @azeezat , right I get it now, but how about the effect of this PR, #91  which is now enforcing labels to be  string internally?

Comment (azeezat) [reply src/utils/index.ts:58]: @kofiarkoh It doesn't affect it, it would cast it.

Comment (kofiarkoh) [reply src/utils/index.ts:58]: okay, sounds good.

**Review by kofiarkoh — APPROVED** [review]
Great. Looks Good.
